GET 127.0.0.1:8084/zeneventserver/api/1.0/heartbeats

###
GET 127.0.0.1:8084/zeneventserver/api/1.0/subscriptions

###
GET 127.0.0.1:8084/zeneventserver/api/1.0/triggers

###
GET 127.0.0.1:8084/zeneventserver/api/1.0/stats

###
GET http://127.0.0.1:8084/zeneventserver/api/1.0/diagnostics/threads

###
